# Generated by Django 3.0 on 2020-07-22 02:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_commnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Commnet',
            new_name='Comment',
        ),
    ]
